### ISSUE TITLE
write a Build guide for mac users

### ISSUE THREAD

**Issue by skriptum** [marpies/protonmail-macos#1]
hi,
first of all i find your project very amazing and would like to test it out. sadly, i am not well versed in Swift, Xcode, and building programs and would need some help there.

Maybe you could write up a guide for newbies how to build the project ourselves?  or even publish a binary for it, if that is not to much overkill. 

Thanks a lot for your help :)

**Comment by marpies** [comment]
Hey,

Thanks! I'll try to release a binary over the weekend.

Cheers

**Comment by marpies** [comment]
I cannot currently sign a build for users outside the Mac App Store due to an issue with my Apple dev account. I've contacted Apple about it so hopefully it'll be resolved quickly. I'll keep you posted.

**Comment by skriptum** [comment]
no problem, dont stress yourself.

**Comment by marpies** [comment]
I published a binary on the [releases page](https://github.com/marpies/protonmail-macos/releases/tag/0.1). Let me know if there's any problem getting it to launch.

**Comment by skriptum** [comment]
wonderful, works like a charm, thanks a lot 👍
